/*
    Generated by Atomist on 06 07 2016 
*/
package com.jackietreehornpublishing;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = Russrest2Application.class)
@WebAppConfiguration
public class Russrest2ApplicationTests {

	@Test
	public void contextLoads() {
	}
}
